apimServiceName: [your target environment apim instance name goes here]
namedValues:
  - name: [name goes here. e.g. environment or SearchEngineBackendURL. It doesn't have to exist in the target environment]
    displayName: [display name  goes here]
    value: [replacement value in the target environment. e.g. name value can be dev in dev environment and prod in the prod environment]
  - name: mynamedvalue
    displayName: mynamedvalue
    keyVault:
      identityClientId: Set if Key Vault authentication happens through a user-assigned managed identity
      secretIdentifier: Url for key vault secret (can be versioned if needed).
loggers:
    - name: [source environment app insight name goes here. e.g. apim-dev-insights]
      loggerType: applicationInsights
      description: [app insight description goes here]
      resourceId: "/subscriptions/[Azure subscription id for the target environment goes here]/resourceGroups/
                   [resource group name for the target environment goes here]/providers/microsoft.insights/components/
                   [target environment app insight name goes here. e.g. apim-prod-insights]"
      credentials:
        instrumentationKey: "destination environment namevalue key for the application insights goes here. You can use the display name to avoid hard coding the key here e.g. {{Logger-Credentials--62390d98217d201158b4bfb3}}. 
                             The assumption is that the namevalue key is already populated in the target environment. This happens automatically when you associate an application insight to your target apim instance"
      isBuffered: true
diagnostics:
   - name: applicationinsights
     verbosity: Error
     loggerId: "/subscriptions/[Azure subscription id for the target environment goes here]/resourceGroups/[resource group name for the target environment goes here]
        /providers/Microsoft.ApiManagement/service/[apim instance name for the target environment goes here]/loggers/[target environment app insight name goes here. e.g. apim-prod-insights]"
apis:
  - name: "[target api version & revision to apply application insights to e.g. 'my-api', 'my-api-v2', 'my-api-v2;rev=2']"
    diagnostics:
      - name: applicationinsights
        verbosity: Error
        loggerId: "/subscriptions/[Azure subscription id for the target environment goes here]/resourceGroups/[resource group name for the target environment goes here]
        /providers/Microsoft.ApiManagement/service/[apim instance name for the target environment goes here]/loggers/[target environment app insight name goes here. e.g. apim-prod-insights]"
        



        
