apimServiceName: apiopsprod
namedValues:
  - name: environment
    displayName: apiopsprod
    value: prod
  - name: apiopsvalue
    displayName: apippsvalue
    keyVault:
      identityClientId: Set if Key Vault authentication happens through a user-assigned managed identity
      secretIdentifier: Url for key vault secret (can be versioned if needed).
loggers:
    - name: apiops-dev-insights
      loggerType: applicationInsights
      description: apiopsapplicationinsights
      resourceId: "/subscriptions/28296629-48b9-4b8c-81f1-35c3ca4fed0a/resourceGroups/apiops-prd-rg/providers/microsoft.insights/components/apim-prod-insights"
      credentials:
        instrumentationKey: "destination environment namevalue key for the application insights goes here. You can use the display name to avoid hard coding the key here e.g. {{Logger-Credentials--62390d98217d201158b4bfb3}}. 
                             The assumption is that the namevalue key is already populated in the target environment. This happens automatically when you associate an application insight to your target apim instance"
      isBuffered: true
diagnostics:
   - name: applicationinsights
     verbosity: Error
     loggerId: "/subscriptions/28296629-48b9-4b8c-81f1-35c3ca4fed0a/resourceGroups/apiops-prd-rg/providers/microsoft.insights/components/apim-prod-insights"
       
apis:
  - name: " 'test','swagger-petstore-openapi-3-0' "
    diagnostics:
      - name: applicationinsights
        verbosity: Error
        loggerId: "/subscriptions/28296629-48b9-4b8c-81f1-35c3ca4fed0a/resourceGroups/apiops-prd-rg/providers/microsoft.insights/components/apim-prod-insights"     



        
